// --- src/router/enums.ts ---
// 完整版菜单比较多，将 rank 抽离出来，在此方便维护
// 平台规定只有 home 路由的 rank 才能为 0
const home = 0,
  chatai = 1,
  vueflow = 2,
  ganttastic = 3,
  components = 4,
  able = 5,
  table = 6,
  form = 7,
  list = 8,
  result = 9,
  error = 10,
  frame = 11,
  nested = 12,
  permission = 13,
  system = 14,
  monitor = 15,
  tabs = 16,
  about = 17,
  codemirror = 18,
  markdown = 19,
  editor = 20,
  flowchart = 21,
  formdesign = 22,
  board = 23,
  ppt = 24,
  mind = 25,
  guide = 26,
  menuoverflow = 27,
  // BI分析中心
  bi_analysis = 30,
  // 运营管理中心
  operations_management = 40,
  product_management = 41,
  store_management = 42,
  employee_management = 43,
  member_management = 44,
  // AI策略中心
  ai_strategy = 50,
  // KPI考核中心
  kpi_assessment = 60,
  // 系统管理
  system_management = 90,
  user_management = 91,
  role_management = 92,
  enterprise_account = 93;

export {
  home,
  chatai,
  vueflow,
  ganttastic,
  components,
  able,
  table,
  form,
  list,
  result,
  error,
  frame,
  nested,
  permission,
  system,
  monitor,
  tabs,
  about,
  codemirror,
  markdown,
  editor,
  flowchart,
  formdesign,
  board,
  ppt,
  mind,
  guide,
  menuoverflow,
  bi_analysis,
  operations_management,
  product_management,
  store_management,
  employee_management,
  member_management,
  ai_strategy,
  kpi_assessment,
  system_management,
  user_management,
  role_management,
  enterprise_account
};
